spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.70.32.163:3306/mise?serverTimezone=UTC
      username: root
      password: 123456
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 9001

xf-rest:
  hostUrl: http://localhost:8080/xf
  sendQuestionUri: /sendQuestion

ai:
  aiId: 0